# -*- mode: ruby -*-
# vi: set ft=ruby :
# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2016, Numenta, Inc.  Unless you have purchased from
# Numenta, Inc. a separate commercial license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------
require 'json'

# Get required 'node' version from 'package.json'
package = JSON.parse(File.read(File.expand_path "../package.json"))
NODE_VERSION = package["engines"]["node"]

Vagrant.configure(2) do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"

  # Additional provisioning for requirements not satisfied by image alone.
  # Arguments:
  #   1) node version
  config.vm.provision "shell", path: "vagrant-provision.sh", args: [NODE_VERSION]

  # Use pseudoterminal.  Required for use in bamboo.
  config.ssh.pty = true

end
